services:
  db:
    image: postgres:17
    container_name: ps_quiz_db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=ps_quiz_clone
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ps_quiz_clone -U user"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ps-quiz-network

  redis:
    image: redis:7-alpine
    container_name: ps_quiz_redis
    ports:
      - "6379:6379"
    networks:
      - ps-quiz-network

  backend:
    build: .
    container_name: ps_quiz_backend
    env_file:
      - .env.bak
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ps_quiz_clone
      - REDIS_HOST=redis
      - SPRING_DATA_REDIS_HOST=redis
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PROTOCOL=${MAIL_PROTOCOL}
    networks:
      - ps-quiz-network

  frontend:
    build: ./frontend
    container_name: ps_quiz_frontend
    env_file:
      - frontend/.env.bak
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - ps-quiz-network

networks:
  ps-quiz-network:
    driver: bridge