services:
  db:
    image: postgres:17
    container_name: ps_quiz_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=ps_quiz_db
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ps_quiz_db -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ps-quiz-network

  redis:
    image: redis:7-alpine
    container_name: ps_quiz_redis
    networks:
      - ps-quiz-network

  backend:
    build: .
    container_name: ps_quiz_backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ps_quiz_db
      - REDIS_HOST=redis
      - SPRING_DATA_REDIS_HOST=redis
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ADDRESS=${APP_ADDRESS}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PROTOCOL=${MAIL_PROTOCOL}
    networks:
      - ps-quiz-network

  frontend:
    build: ./frontend
    container_name: ps_quiz_frontend
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - ps-quiz-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    # Команда для получения сертификата (запустится один раз)
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - ps-quiz-network
networks:
  ps-quiz-network:
    driver: bridge