services:
  db:
    image: postgres:17
    container_name: quizizz_db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=quizizz_clone
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d quizizz_clone -U user"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - quizizz-network

  redis:
    image: redis:7-alpine
    container_name: quizizz_redis
    ports:
      - "6379:6379"
    networks:
      - quizizz-network

  backend:
    build: .
    container_name: quizizz_backend
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quizizz_clone
      - SPRING_DATA_REDIS_HOST=redis
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_PROTOCOL=${MAIL_PROTOCOL}
    networks:
      - quizizz-network

  frontend:
    build: ./frontend
    container_name: quizizz_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - quizizz-network

networks:
  quizizz-network:
    driver: bridge