server:
  port: 8080
app:
  secret: ${APP_JWT_SECRET:TestSecretKeyforlocaldevlnlnnnnbnuytrdcvbnjuytrdcvb}
  cors:
    app-address: ${APP_ADDRESS:http://localhost:3000}
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
  admin:
    email: ${ADMIN_EMAIL:awdiru@gmail.com}

spring:
  application:
    name: quizizz

  mail:
    host: ${MAIL_HOST:smtp.yandex.ru}
    port: 465
    username: ${MAIL_USERNAME:program-shcool@yandex.ru}
    password: ${MAIL_PASSWORD:jlkkhlccvtkygrgn}
    protocol: ${MAIL_PROTOCOL:smtps}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6432/ps_quiz_db}
    username: ${DB_USERNAME:awdiru@gmail.com}
    password: ${DB_PASSWORD:VerySecurityPassword}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG